ExternalProject_Add(external_ftgl
	PREFIX ${CMAKE_BINARY_DIR}/ftgl
	GIT_REPOSITORY ${FTGL_REPO}
	GIT_TAG ${FTGL_TAG}
	GIT_PROGRESS true
	GIT_SHALLOW True
	CMAKE_ARGS -DCMAKE_BUILD_TYPE:String=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${OUTPUT_PATH}/ftgl
	INSTALL_COMMAND ""
					
)


