IF(WITH_LIB_NLOHMANNJSON)
	set(LIB_NLOHMANNJSON_INC_PATH
        ${OUTPUT_PATH}/lib/nlohmannjson/include/
    )

	set(LIB_NLOHMANNJSON_STATIC_LIBS ${PLATFORM_LIBS})
    set(LIB_NLOHMANNJSON_DEPS
        external_nlohmannjson
    )

	set(LIB_NLOHMANNJSON_EXAMPLE_BASIC_COMPILER g++)
	set(LIB_NLOHMANNJSON_EXAMPLE_BASIC_CXX_STANDARD 11)
	set(LIB_NLOHMANNJSON_EXAMPLE_BASIC_CXX_STANDARD_REQUIRED TRUE)
    
	ExternalProject_Add(external_nlohmannjson
		PREFIX ${CMAKE_BINARY_DIR}/nlohmannjson
		URL ${NLOHMANN_JSON_REPO}
		URL_HASH SHA256=${NLOHMANN_JSON_HASH}
		DOWNLOAD_DIR ${CMAKE_BINARY_DIR}/nlohmannjson
		DOWNLOAD_NO_EXTRACT 1
		CONFIGURE_COMMAND ""
		BUILD_COMMAND ""
		INSTALL_COMMAND COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/nlohmannjson/json.hpp ${OUTPUT_PATH}/lib/nlohmannjson/include/nlohmann/json.hpp
	)

ENDIF()
