if(NOT WITH_LIB_NLOHMANN_JSON)
	message(FATAL_ERROR "Error: Try to build example WITH_LIB_NLOHMANN_JSON_EXAMPLE_BASIC without WITH_LIB_GLAD")
endif()

if(WITH_LIB_NLOHMANN_JSON_EXAMPLE_BASIC)
	message(STATUS "Building example WITH_LIB_NLOHMANN_JSON_EXAMPLE_BASIC")
	add_executable(LIB_NLOHMANN_JSON_EXAMPLE_BASIC ${LIB_NLOHMANN_JSON_EXAMPLE_BASIC_SRC})
	set(CMAKE_C_COMPILER ${LIB_NLOHMANN_JSON_EXAMPLE_BASIC_COMPILER})
	set(CMAKE_CXX_STANDARD ${LIB_NLOHMANN_JSON_EXAMPLE_BASIC_CXX_STANDARD})
	set(CMAKE_CXX_STANDARD_REQUIRED ${LIB_NLOHMANN_JSON_EXAMPLE_BASIC_CXX_STANDARD_REQUIRED})

	target_include_directories(LIB_NLOHMANN_JSON_EXAMPLE_BASIC PRIVATE ${LIB_NLOHMANN_JSON_INC_PATH})
	target_link_directories(LIB_NLOHMANN_JSON_EXAMPLE_BASIC PRIVATE ${LIB_NLOHMANN_JSON_LIB_PATH})
	cmake_print_variables(LIB_GLFW_STATIC_LIBS)
	target_link_libraries(LIB_NLOHMANN_JSON_EXAMPLE_BASIC PRIVATE ${LIB_NLOHMANN_JSON_EXAMPLE_BASIC_STATIC_LIBS})
       
	set_target_properties(LIB_NLOHMANN_JSON_EXAMPLE_BASIC PROPERTIES RELEASE_OUTPUT_NAME ${LIB_NLOHMANN_JSON_OUTPUT_NAME_RELEASE})
	set_target_properties(LIB_NLOHMANN_JSON_EXAMPLE_BASIC PROPERTIES DEBUG_OUTPUT_NAME ${LIB_NLOHMANN_JSON_OUTPUT_NAME_DEBUG})

	add_dependencies(LIB_NLOHMANN_JSON_EXAMPLE_BASIC ${LIB_NLOHMANN_JSON_DEPS})
	install(
		TARGETS LIB_NLOHMANN_JSON_EXAMPLE_BASIC
		RUNTIME DESTINATION ${LIB_NLOHMANN_JSON_EXAMPLE_BASIC_INSTALL_PATH}
	)
	install(
		FILES ${CMAKE_SOURCE_DIR}/src/examples/nlohmann_json/basic/configuration.json
		DESTINATION ${OUTPUT_PATH}/examples/nlohmann_json/basic/
	)
endif()

