if(WITH_LIB_EIGEN_EXAMPLE_BASIC)
	if(NOT WITH_LIB_EIGEN)
		message(FATAL_ERROR "Error: Try to build example WITH_LIB_EIGEN_EXAMPLE_BASIC without WITH_LIB_EIGEN")
	endif()

	message(STATUS "Building example WITH_LIB_EIGEN_EXAMPLE_BASIC")

	set(LIB_EIGEN_EXAMPLE_BASIC_SRC
		${CMAKE_SOURCE_DIR}/src/examples/eigen/basic/eigen_basic.cpp
	)
	
	set(LIB_EIGEN_EXAMPLE_BASIC_OUTPUT_NAME_RELEASE eigen-basic)
	set(LIB_EIGEN_EXAMPLE_BASIC_OUTPUT_NAME_DEBUG eigen-basic_d)
	
	set(LIB_EIGEN_EXAMPLE_BASIC_INSTALL_PATH
        ${OUTPUT_PATH}/examples/eigen/basic/
    )

	add_executable(LIB_EIGEN_EXAMPLE_BASIC ${LIB_EIGEN_EXAMPLE_BASIC_SRC})
	set(CMAKE_C_COMPILER ${LIB_EIGEN_EXAMPLE_BASIC_COMPILER})
	set(CMAKE_CXX_STANDARD ${LIB_EIGEN_EXAMPLE_BASIC_CXX_STANDARD})
	set(CMAKE_CXX_STANDARD_REQUIRED ${LIB_EIGEN_EXAMPLE_BASIC_CXX_STANDARD_REQUIRED})

	target_include_directories(LIB_EIGEN_EXAMPLE_BASIC PRIVATE ${LIB_EIGEN_INC_PATH})
	target_link_directories(LIB_EIGEN_EXAMPLE_BASIC PRIVATE ${LIB_EIGEN_LIB_PATH})
	target_link_libraries(LIB_EIGEN_EXAMPLE_BASIC PRIVATE ${LIB_EIGEN_EXAMPLE_BASIC_STATIC_LIBS})
       
	set_target_properties(LIB_EIGEN_EXAMPLE_BASIC PROPERTIES RELEASE_OUTPUT_NAME ${LIB_EIGEN_EXAMPLE_BASIC_OUTPUT_NAME_RELEASE})
	set_target_properties(LIB_EIGEN_EXAMPLE_BASIC PROPERTIES DEBUG_OUTPUT_NAME ${LIB_EIGEN_EXAMPLE_BASIC_OUTPUT_NAME_DEBUG})

	add_dependencies(LIB_EIGEN_EXAMPLE_BASIC ${LIB_EIGEN_DEPS})
	install(
		TARGETS LIB_EIGEN_EXAMPLE_BASIC
		RUNTIME DESTINATION ${LIB_EIGEN_EXAMPLE_BASIC_INSTALL_PATH}
	)
endif()

