if(NOT WITH_LIB_GLAD)
	message(FATAL_ERROR "Error: Try to build example WITH_LIB_GLFW_EXAMPLE_CBASIC without WITH_LIB_GLAD")
endif()
if(NOT WITH_LIB_GLFW)
	message(FATAL_ERROR "Error: Try to build example WITH_LIB_GLFW_EXAMPLE_CBASIC without WITH_LIB_GLFW")
endif()

if(WITH_LIB_GLFW_EXAMPLE_CBASIC)
	message(STATUS "Building example WITH_LIB_GLFW_EXAMPLE_CBASIC")
	add_executable(LIB_GLFW_EXAMPLE_CBASIC ${LIB_GLFW_EXAMPLE_CBASIC_SRC})
	set(CMAKE_C_COMPILER ${LIB_GLFW_EXAMPLE_CBASIC_COMPILER})

	target_include_directories(LIB_GLFW_EXAMPLE_CBASIC PRIVATE ${LIB_GLFW_INC_PATH})
	target_link_directories(LIB_GLFW_EXAMPLE_CBASIC PRIVATE ${LIB_GLFW_LIB_PATH})
	cmake_print_variables(LIB_GLFW_STATIC_LIBS)
	target_link_libraries(LIB_GLFW_EXAMPLE_CBASIC PRIVATE ${LIB_GLFW_STATIC_LIBS})
       
	set_target_properties(LIB_GLFW_EXAMPLE_CBASIC PROPERTIES RELEASE_OUTPUT_NAME ${LIB_GLFW_EXAMPLE_CBASIC_RELEASE_OUTPUT_NAME})
	set_target_properties(LIB_GLFW_EXAMPLE_CBASIC PROPERTIES DEBUG_OUTPUT_NAME ${LIB_GLFW_EXAMPLE_CBASIC_DEBUG_OUTPUT_NAME})

	add_dependencies(LIB_GLFW_EXAMPLE_CBASIC ${LIB_GLFW_EXAMPLE_CBASIC_DEPS})
	install(
		TARGETS LIB_GLFW_EXAMPLE_CBASIC
		RUNTIME DESTINATION ${LIB_GLFW_EXAMPLE_CBASIC_INSTALL_PATH}
	)
endif()
